[2025-05-07T04:19:05.702+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:19:05.705+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:19:05.714+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:19:05.712+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:19:05.773+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:19:05.770+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:19:05.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:19:05.797+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.103 seconds
[2025-05-07T04:19:36.178+0000] {processor.py:186} INFO - Started process (PID=199) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:19:36.179+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:19:36.182+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:19:36.181+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:19:36.228+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:19:36.225+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:19:36.229+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:19:36.247+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.092 seconds
[2025-05-07T04:20:06.778+0000] {processor.py:186} INFO - Started process (PID=213) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:20:06.781+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:20:06.785+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:20:06.784+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:20:06.835+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:20:06.832+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:20:06.836+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:20:06.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.091 seconds
[2025-05-07T04:20:37.274+0000] {processor.py:186} INFO - Started process (PID=241) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:20:37.275+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:20:37.278+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:20:37.278+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:20:37.333+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:20:37.326+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:20:37.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:20:37.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.095 seconds
[2025-05-07T04:21:07.950+0000] {processor.py:186} INFO - Started process (PID=251) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:21:07.952+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:21:07.954+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:21:07.954+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:21:07.988+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:21:07.986+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:21:07.989+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:21:08.007+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.066 seconds
[2025-05-07T04:21:38.441+0000] {processor.py:186} INFO - Started process (PID=261) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:21:38.442+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:21:38.446+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:21:38.445+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:21:38.496+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:21:38.493+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:21:38.497+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:21:38.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.082 seconds
[2025-05-07T04:22:08.940+0000] {processor.py:186} INFO - Started process (PID=271) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:22:08.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:22:08.945+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:22:08.945+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:22:08.989+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:22:08.985+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:22:08.991+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:22:09.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.095 seconds
[2025-05-07T04:22:39.495+0000] {processor.py:186} INFO - Started process (PID=281) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:22:39.496+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:22:39.499+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:22:39.498+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:22:39.559+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:22:39.551+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:22:39.561+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:22:39.585+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.100 seconds
[2025-05-07T04:23:10.164+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:23:10.168+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:23:10.170+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:23:10.170+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:23:10.217+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:23:10.214+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:23:10.219+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:23:10.233+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.091 seconds
[2025-05-07T04:23:40.668+0000] {processor.py:186} INFO - Started process (PID=301) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:23:40.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:23:40.672+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:23:40.672+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:23:40.709+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:23:40.704+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:23:40.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:23:40.727+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.069 seconds
[2025-05-07T04:24:11.223+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:24:11.224+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:24:11.227+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:24:11.226+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:24:11.324+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:24:11.318+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:24:11.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:24:11.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.148 seconds
[2025-05-07T04:24:41.820+0000] {processor.py:186} INFO - Started process (PID=321) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:24:41.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:24:41.824+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:24:41.823+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:24:41.873+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:24:41.867+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:24:41.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:24:41.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.087 seconds
[2025-05-07T04:25:12.312+0000] {processor.py:186} INFO - Started process (PID=331) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:25:12.313+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:25:12.316+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:25:12.315+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:25:12.353+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:25:12.350+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:25:12.355+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:25:12.374+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.071 seconds
[2025-05-07T04:25:42.833+0000] {processor.py:186} INFO - Started process (PID=341) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:25:42.834+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:25:42.836+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:25:42.835+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:25:42.885+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:25:42.882+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:25:42.886+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:25:42.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.079 seconds
[2025-05-07T04:27:20.353+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:27:20.355+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:27:20.358+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:27:20.358+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:27:20.392+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:27:20.388+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:27:20.393+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:27:20.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.062 seconds
[2025-05-07T04:27:50.702+0000] {processor.py:186} INFO - Started process (PID=202) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:27:50.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:27:50.708+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:27:50.707+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:27:50.746+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:27:50.743+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:27:50.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:27:50.764+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.073 seconds
[2025-05-07T04:28:21.122+0000] {processor.py:186} INFO - Started process (PID=241) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:28:21.125+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:28:21.130+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:28:21.130+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:28:21.194+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:28:21.189+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:28:21.196+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:28:21.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.115 seconds
[2025-05-07T04:28:51.580+0000] {processor.py:186} INFO - Started process (PID=302) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:28:51.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:28:51.585+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:28:51.585+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:28:51.614+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:28:51.611+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:28:51.615+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:28:51.630+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.056 seconds
[2025-05-07T04:29:22.306+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:29:22.307+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:29:22.311+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:29:22.311+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:29:22.348+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:29:22.345+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:29:22.350+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:29:22.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.068 seconds
[2025-05-07T04:29:52.784+0000] {processor.py:186} INFO - Started process (PID=365) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:29:52.785+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:29:52.790+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:29:52.789+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:29:52.844+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:29:52.840+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:29:52.846+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:29:52.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.094 seconds
[2025-05-07T04:30:23.288+0000] {processor.py:186} INFO - Started process (PID=375) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:30:23.289+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:30:23.292+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:30:23.291+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:30:23.327+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:30:23.324+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:30:23.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:30:23.344+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.065 seconds
[2025-05-07T04:30:53.762+0000] {processor.py:186} INFO - Started process (PID=385) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:30:53.763+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:30:53.770+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:30:53.769+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:30:53.836+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:30:53.829+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:30:53.838+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:30:53.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.134 seconds
[2025-05-07T04:31:24.271+0000] {processor.py:186} INFO - Started process (PID=395) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:31:24.273+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:31:24.278+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:31:24.277+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:31:24.316+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:31:24.314+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:31:24.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:31:24.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.075 seconds
[2025-05-07T04:31:54.735+0000] {processor.py:186} INFO - Started process (PID=405) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:31:54.736+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:31:54.741+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:31:54.740+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:31:54.789+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:31:54.785+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:31:54.790+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:31:54.809+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.084 seconds
[2025-05-07T04:32:25.279+0000] {processor.py:186} INFO - Started process (PID=415) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:32:25.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:32:25.284+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:32:25.283+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:32:25.323+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:32:25.320+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:32:25.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:32:25.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.070 seconds
[2025-05-07T04:32:55.729+0000] {processor.py:186} INFO - Started process (PID=425) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:32:55.732+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:32:55.736+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:32:55.735+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:32:55.774+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:32:55.772+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:32:55.777+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:32:55.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.075 seconds
[2025-05-07T04:33:26.278+0000] {processor.py:186} INFO - Started process (PID=435) to work on /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:33:26.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/load_raw_data.py for tasks to queue
[2025-05-07T04:33:26.296+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:33:26.295+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:33:26.337+0000] {logging_mixin.py:190} INFO - [2025-05-07T04:33:26.334+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/load_raw_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/load_raw_data.py", line 26, in <module>
    S3_BUCKET = Variable.get('S3_BUCKET')
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable S3_BUCKET does not exist'
[2025-05-07T04:33:26.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/load_raw_data.py
[2025-05-07T04:33:26.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/load_raw_data.py took 0.085 seconds
