[2025-05-03T01:57:40.738+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-03T01:57:40.785+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_snapshot manual__2025-05-03T01:56:53.671700+00:00 [queued]>
[2025-05-03T01:57:40.812+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_snapshot manual__2025-05-03T01:56:53.671700+00:00 [queued]>
[2025-05-03T01:57:40.813+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-03T01:57:40.853+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_snapshot> on 2025-05-03 01:56:53.671700+00:00
[2025-05-03T01:57:40.868+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_snapshot', 'manual__2025-05-03T01:56:53.671700+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp58qvgie0']
[2025-05-03T01:57:40.874+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask dbt_snapshot
[2025-05-03T01:57:40.874+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=317) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-03T01:57:40.880+0000] {standard_task_runner.py:72} INFO - Started process 320 to run task
[2025-05-03T01:57:40.989+0000] {task_command.py:467} INFO - Running <TaskInstance: BuildELT_dbt.dbt_snapshot manual__2025-05-03T01:56:53.671700+00:00 [running]> on host 1f5f9fe55831
[2025-05-03T01:57:41.194+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_snapshot' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T01:56:53.671700+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T01:56:53.671700+00:00'
[2025-05-03T01:57:41.197+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-03T01:57:41.234+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-03T01:57:41.237+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt snapshot --profiles-dir /opt/***/final_project_dbt --project-dir /opt/***/final_project_dbt']
[2025-05-03T01:57:41.255+0000] {subprocess.py:86} INFO - Output:
[2025-05-03T01:57:45.882+0000] {subprocess.py:93} INFO - [0m01:57:45  Running with dbt=1.9.4
[2025-05-03T01:57:48.039+0000] {subprocess.py:93} INFO - [0m01:57:48  Registered adapter: snowflake=1.9.4
[2025-05-03T01:57:49.348+0000] {subprocess.py:93} INFO - [0m01:57:49  Found 8 models, 2 snapshots, 5 data tests, 3 sources, 476 macros
[2025-05-03T01:57:49.358+0000] {subprocess.py:93} INFO - [0m01:57:49
[2025-05-03T01:57:49.360+0000] {subprocess.py:93} INFO - [0m01:57:49  Concurrency: 1 threads (target='dev')
[2025-05-03T01:57:49.363+0000] {subprocess.py:93} INFO - [0m01:57:49
[2025-05-03T01:57:51.265+0000] {subprocess.py:93} INFO - [0m01:57:51  1 of 2 START snapshot snapshot.dashboard_overview_snapshot ..................... [RUN]
[2025-05-03T01:57:56.043+0000] {subprocess.py:93} INFO - [0m01:57:56  1 of 2 OK snapshotted snapshot.dashboard_overview_snapshot ..................... [[32mSUCCESS 0[0m in 4.77s]
[2025-05-03T01:57:56.051+0000] {subprocess.py:93} INFO - [0m01:57:56  2 of 2 START snapshot snapshot.player_ranking_history_snapshot ................. [RUN]
[2025-05-03T02:04:59.388+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2025-05-03T02:04:59.877+0000] {process_utils.py:132} INFO - Sending 15 to group 320. PIDs of all processes in the group: [322, 332, 320]
[2025-05-03T02:04:59.902+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 320
[2025-05-03T02:05:00.159+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-03T02:05:00.420+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-05-03T02:05:00.653+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 240, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-05-03T02:05:00.738+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_snapshot, run_id=manual__2025-05-03T01:56:53.671700+00:00, execution_date=20250503T015653, start_date=20250503T015740, end_date=20250503T020500
[2025-05-03T02:05:00.839+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-03T02:05:00.862+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=320, status='terminated', exitcode=2, started='01:57:40') (320) terminated with exit code 2
[2025-05-03T02:05:00.864+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=332, status='terminated', started='01:57:47') (332) terminated with exit code None
[2025-05-03T02:05:00.866+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=322, status='terminated', started='01:57:40') (322) terminated with exit code None
[2025-05-03T02:05:00.869+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2025-05-03T02:05:00.931+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T02:05:01.133+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-05-03T02:05:01.651+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
